### ISSUE TITLE
Traceback (most recent call last):   File "db.py", line 4, in <module>     from run import app ImportError: cannot import name 'app'

### ISSUE THREAD

**Issue by Althea-Lobo** [Leo-g/Flask-Skeleton#1]
Got the above error while migrating, you need to change the code in run.py to 

#!/usr/bin/env python
from app import create_app

app = create_app('config')

if __name__ == '__main__':
    app.run(host=app.config['HOST'],
            port=app.config['PORT'],
            debug=app.config['DEBUG'])

**Comment by Leo-g** [comment]
https://github.com/Leo-g/Flask-Skeleton/pull/2
